import { createSlice } from "@reduxjs/toolkit";

//icons
import { ImStarFull } from "react-icons/im";
import { ImStarEmpty } from "react-icons/im";
import { ImStarHalf } from "react-icons/im";

const ProductsPageSlice = createSlice({
  name: "products",
  initialState: {
    allProducts: [
      {
        id: 1,
        image: "../../../product-1.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "86",
        description:
          "Give your summer wardrobe a style upgrade with the HRX Men's Active T-Shirt. Team it with  a pair of shorts for your morning wourkout or a denims for an evening out with the guys",
        smalls: [
          { id: 1, small: "../../../gallery-1.jpg" },
          { id: 2, small: "../../../gallery-2.jpg" },
          { id: 3, small: "../../../gallery-3.jpg" },
          { id: 4, small: "../../../gallery-4.jpg" },
        ],
      },

      {
        id: 2,
        image: "../../../product-2.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "85",
      },
      {
        id: 3,
        image: "../../../product-3.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "84",
      },
      {
        id: 4,
        image: "../../../product-4.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "83",
      },
      {
        id: 5,
        image: "../../../product-5.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "82",
      },
      {
        id: 6,
        image: "../../../product-6.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "81",
      },
      {
        id: 7,
        image: "../../../product-7.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "80",
      },
      {
        id: 8,
        image: "../../../product-8.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "79",
      },
      {
        id: 9,
        image: "./images/../../../product-9.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "78",
      },
      {
        id: 10,
        image: "../../../product-10.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "77",
      },
      {
        id: 11,
        image: "../../../product-11.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "76",
      },
      {
        id: 12,
        image: "../../../product-12.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "75",
      },
      {
        id: 13,
        image: "../../../product-1.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "74",
      },
      {
        id: 14,
        image: "../../../product-2.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "73",
      },
      {
        id: 15,
        image: "./images/../../../product-3.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "72",
      },
      {
        id: 16,
        image: "./images/../../../product-4.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "71",
      },
      {
        id: 17,
        image: "./images/../../../product-5.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "70",
      },
      {
        id: 18,
        image: "./images/../../../product-6.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "69",
      },
      {
        id: 19,
        image: "./images/../../../product-7.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "68",
      },
      {
        id: 20,
        image: "./images/../../../product-8.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "67",
      },
      {
        id: 21,
        image: "./images/../../../product-9.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "66",
      },
      {
        id: 22,
        image: "./images/../../../product-10.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "65",
      },
      {
        id: 23,
        image: "./images/../../../product-11.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "64",
      },
      {
        id: 24,
        image: "./images/../../../product-12.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "63",
      },
      {
        id: 25,
        image: "./images/../../../product-1.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "62",
      },
      {
        id: 26,
        image: "./images/../../../product-2.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "61",
      },
      {
        id: 27,
        image: "./images/../../../product-3.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "60",
      },
      {
        id: 28,
        image: "./images/../../../product-4.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "59",
      },
      {
        id: 29,
        image: "./images/../../../product-5.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "58",
      },
      {
        id: 30,
        image: "./images/../../../product-6.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "57",
      },
      {
        id: 31,
        image: "./images/../../../product-7.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "56",
      },
      {
        id: 32,
        image: "./images/../../../product-8.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "55",
      },
      {
        id: 33,
        image: "./images/../../../product-9.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "54",
      },
      {
        id: 34,
        image: "./images/../../../product-10.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "53",
      },
      {
        id: 35,
        image: "./images/../../../product-11.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "52",
      },
      {
        id: 36,
        image: "./images/../../../product-12.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "51",
      },
      {
        id: 37,
        image: "./images/../../../product-1.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "86",
      },
      {
        id: 38,
        image: "./images/../../../product-2.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "85",
      },
      {
        id: 39,
        image: "./images/../../../product-3.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "84",
      },
      {
        id: 40,
        image: "./images/../../../product-4.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "83",
      },
      {
        id: 41,
        image: "./images/../../../product-5.jpg",
        name: "Red Printed",
        i1: <ImStarFull />,
        i2: <ImStarFull />,
        i3: <ImStarFull />,
        i4: <ImStarHalf />,
        i5: <ImStarEmpty />,
        cost: "82",
      },
    ],
  },
});

export default ProductsPageSlice.reducer;
